// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITS.BiblioAccess.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250310044634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ITS.BiblioAccess.Domain.Entities.Career", b =>
                {
                    b.Property<Guid>("CareerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("CareerId");

                    b.ToTable("Careers");
                });

            modelBuilder.Entity("ITS.BiblioAccess.Domain.Entities.EntryRecord", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CareerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId");

                    b.ToTable("EntryRecords");
                });

            modelBuilder.Entity("ITS.BiblioAccess.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<Guid>("SystemConfigurationId")
                        .HasColumnType("TEXT");

                    b.HasKey("SystemConfigurationId");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("ITS.BiblioAccess.Domain.Entities.Career", b =>
                {
                    b.OwnsOne("ITS.BiblioAccess.Domain.ValueObjects.CareerName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CareerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("CareerId");

                            b1.ToTable("Careers");

                            b1.WithOwner()
                                .HasForeignKey("CareerId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ITS.BiblioAccess.Domain.Entities.SystemConfiguration", b =>
                {
                    b.OwnsOne("ITS.BiblioAccess.Domain.ValueObjects.ExportHour", "ExportHour", b1 =>
                        {
                            b1.Property<Guid>("SystemConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("ExportHour");

                            b1.HasKey("SystemConfigurationId");

                            b1.ToTable("SystemConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("SystemConfigurationId");
                        });

                    b.Navigation("ExportHour")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
